require: rubocop-bridgetown

inherit_gem:
  rubocop-bridgetown: .rubocop.yml

AllCops:
  TargetRubyVersion: 2.5
  Include:
    - lib/**/*.rb
    - test/**/*.rb

  Exclude:
    - .gitignore
    - .rubocop.yml

    - Gemfile.lock
    - CHANGELOG.md
    - LICENSE.txt
    - README.md

    - script/**/*
    - vendor/**/*
