name: CI Test

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BUNDLE_JOBS: 4
      BUNDLE_PATH: "vendor/bundle"
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby and Yarn
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
        bundler-cache: true
    - uses: actions/setup-node@v2
      with:
        node-version: '22'
    - name: Install NPM packages
      run: npm install
    - name: Run tests
      run: script/cibuild
